apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat:34
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat:34
  template:
    metadata:
      labels:
        app: tomcat:34
    spec: 
      containers:
      - name: tomcat:34
        image: tdtuan146/tomcat:34
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dockerhub      
---
apiVersion: v1
kind: Service
metadata:
  name: my-tomcat:34
spec:
  type: NodePort
  ports:
  - port: 8080        # service port mapping into POD
    targetPort: 80    # pod port mapping into container
    protocol: TCP
    name: http
    nodePort: 3008   # node port mapping into service ( 30000-32767)

  #label Deployment
  selector:
    app: tomcat:34
