apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat:43
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat:43
  template:
    metadata:
      labels:
        app: tomcat:43
    spec: 
      containers:
      - name: tomcat:43
        image: tdtuan146/tomcat:43
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dockerhub      
---
